Header test
WildCodeSchool/nts-js-202103-p2-autopartage pull request #1
Opened 2021-04-14 12:18 UTC by GUIGANTONDamien

2021-04-14 12:35 UTC, bastienwcs requested changes

2021-04-14 12:35 UTC, bastienwcs commented on .eslintrc.json
> -  "env": {
il ne fait pas modifier ce fichier, remettre le fichier comme il était à l'origine
https://gist.github.com/bastienwcs/6bb405c2e3387c0ee18424bb78de64d4

2021-04-14 12:35 UTC, bastienwcs commented on package.json
> +    "eslint-config-airbnb-base": "^14.2.1",
retirer le module : 
eslint-config-airbnb-base

2021-04-14 13:14 UTC, bastienwcs commented
Y'a le fichier package.json à modifier aussi pour retirer la ligne sur eslint-config-airbnb-base

2021-04-16 09:38 UTC, jonathan-rousseau commented
C'est OK!

2021-04-16 09:42 UTC, bastienwcs commented
Je peux vous aider pour finaliser la pull request si vous voulez :)

2021-04-16 10:21 UTC, closed without merging